name: mobile_teori_tugas3
description: "EclipseOps — Aplikasi Staff Kelola Konser Idol"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.13.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Font Poppins (heading) & Inter (body) sesuai desain UI EclipseOps
  google_fonts: ^6.2.1

  # Untuk komunikasi ke API PHP (login, CRUD konser, dll)
  http: ^1.2.2

  # Untuk session management (menyimpan status login)
  shared_preferences: ^2.3.3

  # Untuk konversi kalender hijriah 
  hijri_date_time: ^1.1.0 

  # Untuk memformat tanggal dan angka sesuai standar internasional 
  intl: ^0.19.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
