// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxcmMmFUuFNIHqSLwLdBCY977035Bjozk',
    appId: '1:680214394530:web:923b7ceda3671eb88e09fb',
    messagingSenderId: '680214394530',
    projectId: 'mobile-tugas3-eclipse-anind',
    authDomain: 'mobile-tugas3-eclipse-anind.firebaseapp.com',
    storageBucket: 'mobile-tugas3-eclipse-anind.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGrZd5hUITHQ8MFom253su63xZVlG1a-I',
    appId: '1:680214394530:android:30f722555417d57d8e09fb',
    messagingSenderId: '680214394530',
    projectId: 'mobile-tugas3-eclipse-anind',
    storageBucket: 'mobile-tugas3-eclipse-anind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcwtbpjx3fCVJWyDlOb1e0iilxNzwz-_Q',
    appId: '1:680214394530:ios:f19b6dbbb11eb6f48e09fb',
    messagingSenderId: '680214394530',
    projectId: 'mobile-tugas3-eclipse-anind',
    storageBucket: 'mobile-tugas3-eclipse-anind.firebasestorage.app',
    iosBundleId: 'com.example.mobileTeoriTugas3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcwtbpjx3fCVJWyDlOb1e0iilxNzwz-_Q',
    appId: '1:680214394530:ios:f19b6dbbb11eb6f48e09fb',
    messagingSenderId: '680214394530',
    projectId: 'mobile-tugas3-eclipse-anind',
    storageBucket: 'mobile-tugas3-eclipse-anind.firebasestorage.app',
    iosBundleId: 'com.example.mobileTeoriTugas3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxcmMmFUuFNIHqSLwLdBCY977035Bjozk',
    appId: '1:680214394530:web:40da90553826a7828e09fb',
    messagingSenderId: '680214394530',
    projectId: 'mobile-tugas3-eclipse-anind',
    authDomain: 'mobile-tugas3-eclipse-anind.firebaseapp.com',
    storageBucket: 'mobile-tugas3-eclipse-anind.firebasestorage.app',
  );
}
